import { Voice, Tone } from './types';

export const VOICES: Voice[] = [
  {
    id: 'vc_1',
    name: 'صوت محايد (رجل)',
    apiName: 'Kore',
    gender: 'male',
    characteristics: 'واضح ومحايد',
    useCase: 'المحتوى التعليمي والإعلانات.',
  },
  {
    id: 'vc_2',
    name: 'صوت درامي (رجل)',
    apiName: 'Fenrir',
    gender: 'male',
    characteristics: 'عميق ومعبر',
    useCase: 'المقاطع الدرامية والقصص.',
  },
  {
    id: 'vc_3',
    name: 'صوت محايد (امرأة)',
    apiName: 'Puck',
    gender: 'female',
    characteristics: 'لطيف وموثوق به',
    useCase: 'الكتب المسموعة والبودكاست.',
  },
  {
    id: 'vc_4',
    name: 'صوت حماسي (امرأة)',
    apiName: 'Zephyr',
    gender: 'female',
    characteristics: 'نشيط وحيوي',
    useCase: 'إعلانات الفيديو والترويج.',
  },
  {
    id: 'vc_5',
    name: 'صوت حكواتي',
    apiName: 'Charon',
    gender: 'male',
    characteristics: 'كلاسيكي ومثالي',
    useCase: 'رواية القصص والحكايات.',
  },
  {
    id: 'vc_6',
    name: 'صوت طفل',
    apiName: 'Kore', // API doesn't have a specific child voice, using a higher pitched voice as substitute
    gender: 'child',
    characteristics: 'طفولي وبريء',
    useCase: 'محتوى الرسوم المتحركة والتعليم.',
  },
  {
    id: 'vc_7',
    name: 'المعلق الوثائقي',
    apiName: 'Charon',
    gender: 'male',
    characteristics: 'رصين ومناسب',
    useCase: 'أفلام الطبيعة والتاريخ.',
  },
  {
    id: 'vc_8',
    name: 'مقدمة الأخبار',
    apiName: 'Puck',
    gender: 'female',
    characteristics: 'مهني وموثوق',
    useCase: 'نشرات الأخبار والتقارير.',
  },
  {
    id: 'vc_9',
    name: 'المذيع الإذاعي',
    apiName: 'Fenrir',
    gender: 'male',
    characteristics: 'جذاب وعميق',
    useCase: 'البرامج الإذاعية والإعلانات الصوتية.',
  },
  {
    id: 'vc_10',
    name: 'المدربة الشخصية',
    apiName: 'Zephyr',
    gender: 'female',
    characteristics: 'محفز وواضح',
    useCase: 'التمارين الرياضية والإرشادات.',
  },
  {
    id: 'vc_11',
    name: 'الأستاذ الجامعي',
    apiName: 'Kore',
    gender: 'male',
    characteristics: 'أكاديمي وهادئ',
    useCase: 'المحاضرات والمواد التعليمية.',
  },
  {
    id: 'vc_12',
    name: 'الجدة الحنونة',
    apiName: 'Puck',
    gender: 'female',
    characteristics: 'دافئ وحنون',
    useCase: 'قصص الأطفال والنصائح.',
  },
  {
    id: 'vc_13',
    name: 'بطل أكشن',
    apiName: 'Fenrir',
    gender: 'male',
    characteristics: 'قوي وحاسم',
    useCase: 'شخصيات ألعاب الفيديو والإعلانات التشويقية.',
  },
  {
    id: 'vc_14',
    name: 'المساعدة الرقمية',
    apiName: 'Zephyr',
    gender: 'female',
    characteristics: 'واضح وودود',
    useCase: 'التطبيقات والأنظمة الذكية.',
  },
  {
    id: 'vc_15',
    name: 'المحاور الهادئ',
    apiName: 'Charon',
    gender: 'male',
    characteristics: 'هادئ ومتزن',
    useCase: 'المقابلات والبودكاست الحواري.',
  },
  {
    id: 'vc_16',
    name: 'صوت التأمل',
    apiName: 'Puck',
    gender: 'female',
    characteristics: 'هادئ ومريح',
    useCase: 'جلسات التأمل والاسترخاء.',
  },
];


export const TONES: Tone[] = [
    { id: 'neutral', name: 'محايد', prompt: '' },
    { id: 'news_anchor', name: 'مذيع أخبار', prompt: 'In the tone of a news anchor, say' },
    { id: 'political_analyst', name: 'محلل سياسي', prompt: 'In the tone of a professional political analyst, say' },
    { id: 'documentary', name: 'معلق وثائقي', prompt: 'In the tone of a documentary narrator, say' },
    { id: 'drama', name: 'أداء درامي', prompt: 'Say dramatically' },
    { id: 'thriller', name: 'إثارة وتشويق', prompt: 'Say with a suspenseful and thrilling tone' },
    { id: 'advertisement', name: 'إعلان تجاري', prompt: 'Say in an energetic and persuasive advertising tone' },
    { id: 'storyteller', name: 'راوي قصص', prompt: 'In the tone of a captivating storyteller, say' },
    { id: 'formal', name: 'خطاب رسمي', prompt: 'Say in a formal tone' },
    { id: 'elearning', name: 'مدرب تعليمي', prompt: 'In a clear and instructive tone, as if for an e-learning course, say' },
];